// GENERATED by scripts/refresh-prices.mjs — do not edit by hand.
//
// Source: the public EC2 on-demand price feed that the AWS pricing page renders.
//   https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ec2-ondemand-without-sec-sel/US%20East%20(N.%20Virginia)/Linux/index.json
// No credentials are needed to reproduce this: re-run `node scripts/refresh-prices.mjs`.
//
// `fetchedAt` is when WE read it. `publishedAt` is when AWS published that price file. Both
// are recorded because they are different facts, and the second is the one that says how
// current the numbers themselves are.
import type { Architecture } from '@rockysurf/provider-sdk'

export const AWS_PRICES_FETCHED_AT = '2026-08-12T04:27:54.539Z'
export const AWS_PRICES_PUBLISHED_AT = '2026-08-10T21:57:58Z'
export const AWS_PRICES_SOURCE = 'https://b0.p.awsstatic.com/pricing/2.0/meteredUnitMaps/ec2/USD/current/ec2-ondemand-without-sec-sel/US%20East%20(N.%20Virginia)/Linux/index.json'

export interface AwsTypeSpec {
  id: string
  cpu: number
  memoryGb: number
  arch: Architecture
}

/** Shape read from the same feed row as the price, so the two cannot disagree. */
export const AWS_TYPES: AwsTypeSpec[] = [
  {
    id: "t3.2xlarge",
    cpu: 8,
    memoryGb: 32,
    arch: "amd64"
  },
  {
    id: "t3.large",
    cpu: 2,
    memoryGb: 8,
    arch: "amd64"
  },
  {
    id: "t3.medium",
    cpu: 2,
    memoryGb: 4,
    arch: "amd64"
  },
  {
    id: "t3.micro",
    cpu: 2,
    memoryGb: 1,
    arch: "amd64"
  },
  {
    id: "t3.nano",
    cpu: 2,
    memoryGb: 0.5,
    arch: "amd64"
  },
  {
    id: "t3.small",
    cpu: 2,
    memoryGb: 2,
    arch: "amd64"
  },
  {
    id: "t3.xlarge",
    cpu: 4,
    memoryGb: 16,
    arch: "amd64"
  },
  {
    id: "t4g.2xlarge",
    cpu: 8,
    memoryGb: 32,
    arch: "arm64"
  },
  {
    id: "t4g.large",
    cpu: 2,
    memoryGb: 8,
    arch: "arm64"
  },
  {
    id: "t4g.medium",
    cpu: 2,
    memoryGb: 4,
    arch: "arm64"
  },
  {
    id: "t4g.micro",
    cpu: 2,
    memoryGb: 1,
    arch: "arm64"
  },
  {
    id: "t4g.nano",
    cpu: 2,
    memoryGb: 0.5,
    arch: "arm64"
  },
  {
    id: "t4g.small",
    cpu: 2,
    memoryGb: 2,
    arch: "arm64"
  },
  {
    id: "t4g.xlarge",
    cpu: 4,
    memoryGb: 16,
    arch: "arm64"
  }
]

/** region → instance type → USD/hour, on-demand Linux, VAT/tax exclusive. */
export const AWS_HOURLY_USD: Record<string, Record<string, number>> = {
  "us-east-1": {
    "t3.2xlarge": 0.3328,
    "t3.large": 0.0832,
    "t3.medium": 0.0416,
    "t3.micro": 0.0104,
    "t3.nano": 0.0052,
    "t3.small": 0.0208,
    "t3.xlarge": 0.1664,
    "t4g.2xlarge": 0.2688,
    "t4g.large": 0.0672,
    "t4g.medium": 0.0336,
    "t4g.micro": 0.0084,
    "t4g.nano": 0.0042,
    "t4g.small": 0.0168,
    "t4g.xlarge": 0.1344
  }
}
