import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it } from 'vitest'
import {
  RegistryIndexError,
  buildRegistryIndex,
  registryIndexSchema,
  renderRegistryIndex,
  sha256File,
  sha256Text,
  type IndexSourceDir,
} from './registry-index.js'

/**
 * The registry index — the document a registry publishes and every client reads.
 *
 * Most of what is asserted here is refusal. The index is generated by a registry's CI and read
 * by every control plane that browses it, so the ways it can be wrong are ways an operator ends
 * up installing something other than what they chose: a path that escapes the registry, a digest
 * that does not describe the file it names, two files claiming one pack id.
 *
 * Note what the index does NOT carry: a trust label. That is asserted too, in "the schema a
 * client validates against" — a pack's label comes from where the operator got it, never from a
 * document the registry itself wrote.
 */

const shippedPacksDir = fileURLToPath(new URL('../../../../packs/', import.meta.url))

const scratch: string[] = []
afterEach(() => {
  for (const dir of scratch.splice(0)) rmSync(dir, { recursive: true, force: true })
})

const TOOL = {
  toolId: 'a-tool',
  name: 'A tool',
  description: 'Does a thing',
  category: 'base',
  url: 'https://example.com',
  installScript: 'echo hi\n',
  enabled: true,
  installOrder: 30,
  bootstrap: false,
  runAs: 'root',
}

/** A registry root with `packs/<group>/` directories under it, as the real layout has. */
function registryWith(groups: Record<string, Record<string, unknown>>): { root: string; sources: IndexSourceDir[] } {
  const root = mkdtempSync(join(tmpdir(), 'rockysurf-registry-'))
  scratch.push(root)
  const sources: IndexSourceDir[] = []
  for (const [group, files] of Object.entries(groups)) {
    const prefix = `packs/${group}`
    const dir = join(root, prefix)
    mkdirSync(dir, { recursive: true })
    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(dir, name), typeof content === 'string' ? content : JSON.stringify(content))
    }
    sources.push({ dir, prefix })
  }
  return { root, sources }
}

const packFile = (packId: string, tools: string[], defines: object[] = []) => ({
  version: 1,
  pack: { packId, name: packId, tools, displayOrder: 10, enabled: true },
  tools: defines,
})

const FIXED = () => new Date('2026-08-14T00:00:00.000Z')

describe('building an index', () => {
  it('describes each pack with its path and digest', () => {
    const { root, sources } = registryWith({
      one: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
    })
    const index = buildRegistryIndex({ sources, now: FIXED })

    expect(registryIndexSchema.safeParse(index).success).toBe(true)
    expect(index.packs).toHaveLength(1)
    expect(index.packs[0]).toMatchObject({
      packId: 'base',
      path: 'packs/one/base.yaml',
      definesTools: ['a-tool'],
      referencesTools: [],
    })
    // The digest has to describe the file a client will fetch, not a re-serialisation of it.
    expect(index.packs[0]!.sha256).toBe(sha256File(join(root, 'packs/one/base.yaml')))
  })

  it('separates the tools a pack defines from the ones it merely references', () => {
    // This is what the pre-install disclosure is built from: "this pack brings X and expects Y
    // to already be here" is a different sentence from "this pack brings X and Y".
    const { sources } = registryWith({
      one: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
      two: { 'extra.yaml': packFile('extra', ['a-tool', 'own'], [{ ...TOOL, toolId: 'own' }]) },
    })
    const index = buildRegistryIndex({ sources, now: FIXED })
    const extra = index.packs.find((p) => p.packId === 'extra')!
    expect(extra).toMatchObject({ definesTools: ['own'], referencesTools: ['a-tool'] })
  })

  it('resolves a reference across source directories rather than rejecting it', () => {
    const { sources } = registryWith({
      one: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
      two: { 'borrows.yaml': packFile('borrows', ['a-tool']) },
    })
    expect(buildRegistryIndex({ sources, now: FIXED }).packs.map((p) => p.packId)).toEqual(['base', 'borrows'])
  })

  it('resolves a reference against --base-packs, which the shop cannot supply itself', () => {
    // THE CASE THE WHOLE REGISTRY DEPENDS ON, under the split-horizon ruling. The shop is purely
    // community; the shared base toolchain a pack is told to REFERENCE rather than redefine
    // ships in the Rocky Surf tarball and is not in the registry at all. Without this the index
    // could never be generated for a single well-behaved contribution.
    const { sources } = registryWith({ community: { 'borrows.yaml': packFile('borrows', ['claude-code']) } })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(/unknown tool "claude-code"/)
    const index = buildRegistryIndex({ sources, basePacksDirs: [shippedPacksDir], now: FIXED })
    expect(index.packs.map((p) => p.packId)).toEqual(['borrows'])
    expect(index.packs[0]!.referencesTools).toEqual(['claude-code'])
  })

  it('is stable: same registry, same bytes', () => {
    // The index is committed by CI. One that churns on every run buries the one diff a reviewer
    // needs under noise, and makes "nothing changed" indistinguishable from "something did".
    const { sources } = registryWith({
      packs: { 'b.yaml': packFile('b', ['a-tool'], [TOOL]), 'a.yaml': packFile('a', ['a-tool']) },
    })
    const first = renderRegistryIndex(buildRegistryIndex({ sources, now: FIXED }))
    const second = renderRegistryIndex(buildRegistryIndex({ sources, now: FIXED }))
    expect(first).toBe(second)
    expect(JSON.parse(first).packs.map((p: { packId: string }) => p.packId)).toEqual(['a', 'b'])
  })

  it('can index this repository’s own packs, which is the fixture nearest to a real registry', () => {
    const index = buildRegistryIndex({ sources: [{ dir: shippedPacksDir, prefix: 'packs' }], now: FIXED })
    expect(index.packs.length).toBeGreaterThan(0)
    expect(registryIndexSchema.safeParse(index).success).toBe(true)
  })
})

describe('refusals', () => {
  it('refuses a registry holding a pack that does not load', () => {
    // Skipping it instead would make "this pack was deleted" and "this pack is broken" look
    // identical to every client, and only one of those is something to tell somebody about.
    const { sources } = registryWith({ packs: { 'broken.yaml': 'pack: [unclosed\n' } })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(RegistryIndexError)
  })

  it('refuses a reference nothing satisfies', () => {
    const { sources } = registryWith({ packs: { 'x.yaml': packFile('x', ['nowhere']) } })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(/unknown tool "nowhere"/)
  })

  it('refuses one packId claimed by two directories', () => {
    // A client resolves a pack by id, so two files claiming one id means whichever it picks is
    // arbitrary — and an operator who installed "the other one" has no way to tell.
    const { sources } = registryWith({
      one: { 'dup.yaml': packFile('dup', ['a-tool'], [TOOL]) },
      two: { 'dup.yaml': packFile('dup', ['a-tool']) },
    })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(/one id, one home/)
  })
})

describe('the schema a client validates against', () => {
  const valid = () => buildRegistryIndex({
    sources: registryWith({ packs: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) } }).sources,
    now: FIXED,
  })

  it.each([
    ['a path escaping the registry', '../../../etc/passwd.yaml'],
    ['an absolute path', '/etc/passwd.yaml'],
    ['traversal in the middle', 'packs/../../secret.yaml'],
    ['a non-YAML file', 'packs/base.sh'],
  ])('rejects %s', (_label, path) => {
    // Core joins `path` onto a base URL. Without this the index decides what gets fetched, and
    // an index is a file in a repository anyone can send a pull request to.
    const index = { ...valid(), packs: [{ ...valid().packs[0]!, path }] }
    expect(registryIndexSchema.safeParse(index).success).toBe(false)
  })

  it('rejects a digest that is not a lowercase hex sha256', () => {
    for (const sha256 of ['', 'nothex', 'ABCD'.repeat(16), 'a'.repeat(63)]) {
      const index = { ...valid(), packs: [{ ...valid().packs[0]!, sha256 }] }
      expect(registryIndexSchema.safeParse(index).success, sha256).toBe(false)
    }
  })

  it('rejects an unknown version, so a future format cannot be silently misread', () => {
    expect(registryIndexSchema.safeParse({ ...valid(), version: 2 }).success).toBe(false)
  })

  it('rejects a trust label, because the index is not where trust is recorded', () => {
    // The owner's split-horizon ruling: a pack's label comes from where the OPERATOR got it —
    // the tarball, or the registry entry in their own config — never from a document the
    // registry itself wrote. A `tier` field would be a trustworthiness claim by the party being
    // trusted, so the schema is strict and refuses it outright rather than ignoring it.
    const index = { ...valid(), packs: [{ ...valid().packs[0]!, tier: 'official' }] }
    expect(registryIndexSchema.safeParse(index).success).toBe(false)
  })

  it('rejects an unknown key rather than ignoring it', () => {
    expect(registryIndexSchema.safeParse({ ...valid(), signature: 'looks-official' }).success).toBe(false)
  })
})

describe('digests', () => {
  it('sha256Text over a file’s content equals sha256File over the file', () => {
    // The install path verifies what the CDN returned, which arrives as text. If the two
    // digests disagreed, every install would fail a check nothing was wrong with — so the pair
    // is asserted rather than assumed.
    const { root } = registryWith({ one: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) } })
    const path = join(root, 'packs/one/base.yaml')
    expect(sha256File(path)).toBe(sha256Text(readFileSync(path, 'utf8')))
    expect(sha256File(path)).toHaveLength(64)
  })
})
