import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, describe, expect, it } from 'vitest'
import {
  RegistryIndexError,
  buildRegistryIndex,
  registryIndexSchema,
  renderRegistryIndex,
  sha256File,
  sha256Text,
  type IndexSourceDir,
} from './registry-index.js'

/**
 * The registry index — the document that carries the trust labels.
 *
 * Most of what is asserted here is refusal. The index is generated by a registry's CI and read
 * by every control plane that browses that registry, so the ways it can be wrong are ways an
 * operator ends up installing something other than what they chose: a path that escapes the
 * registry, a digest that does not describe the file it names, a community pack shadowing an
 * official id.
 */

const shippedPacksDir = fileURLToPath(new URL('../../../../packs/', import.meta.url))

const scratch: string[] = []
afterEach(() => {
  for (const dir of scratch.splice(0)) rmSync(dir, { recursive: true, force: true })
})

const TOOL = {
  toolId: 'a-tool',
  name: 'A tool',
  description: 'Does a thing',
  category: 'base',
  url: 'https://example.com',
  installScript: 'echo hi\n',
  enabled: true,
  installOrder: 30,
  bootstrap: false,
  runAs: 'root',
}

/** A registry root with `packs/<tier>/` directories under it, as the real layout has. */
function registryWith(tiers: Record<string, Record<string, unknown>>): { root: string; sources: IndexSourceDir[] } {
  const root = mkdtempSync(join(tmpdir(), 'rockysurf-registry-'))
  scratch.push(root)
  const sources: IndexSourceDir[] = []
  for (const [tier, files] of Object.entries(tiers)) {
    const prefix = `packs/${tier}`
    const dir = join(root, prefix)
    mkdirSync(dir, { recursive: true })
    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(dir, name), typeof content === 'string' ? content : JSON.stringify(content))
    }
    sources.push({ dir, prefix, tier: tier as 'official' | 'community' })
  }
  return { root, sources }
}

const packFile = (packId: string, tools: string[], defines: object[] = []) => ({
  version: 1,
  pack: { packId, name: packId, tools, displayOrder: 10, enabled: true },
  tools: defines,
})

const FIXED = () => new Date('2026-08-14T00:00:00.000Z')

describe('building an index', () => {
  it('describes each pack with its tier, path and digest', () => {
    const { root, sources } = registryWith({
      official: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
    })
    const index = buildRegistryIndex({ sources, now: FIXED })

    expect(registryIndexSchema.safeParse(index).success).toBe(true)
    expect(index.packs).toHaveLength(1)
    expect(index.packs[0]).toMatchObject({
      packId: 'base',
      tier: 'official',
      path: 'packs/official/base.yaml',
      definesTools: ['a-tool'],
      referencesTools: [],
    })
    // The digest has to describe the file a client will fetch, not a re-serialisation of it.
    expect(index.packs[0]!.sha256).toBe(sha256File(join(root, 'packs/official/base.yaml')))
  })

  it('separates the tools a pack defines from the ones it merely references', () => {
    // This is what the pre-install disclosure is built from: "this pack brings X and expects Y
    // to already be here" is a different sentence from "this pack brings X and Y".
    const { sources } = registryWith({
      official: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
      community: { 'extra.yaml': packFile('extra', ['a-tool', 'own'], [{ ...TOOL, toolId: 'own' }]) },
    })
    const index = buildRegistryIndex({ sources, now: FIXED })
    const extra = index.packs.find((p) => p.packId === 'extra')!
    expect(extra).toMatchObject({ tier: 'community', definesTools: ['own'], referencesTools: ['a-tool'] })
  })

  it('resolves a reference across tiers rather than rejecting it', () => {
    // THE CASE THE WHOLE REGISTRY DEPENDS ON. A community pack is told to reference the shared
    // base toolchain rather than redefine it, and that toolchain is in the official tier. An
    // indexer that judged each directory alone would reject every well-behaved contribution.
    const { sources } = registryWith({
      official: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) },
      community: { 'borrows.yaml': packFile('borrows', ['a-tool']) },
    })
    expect(buildRegistryIndex({ sources, now: FIXED }).packs.map((p) => p.packId)).toEqual(['base', 'borrows'])
  })

  it('is stable: same registry, same bytes', () => {
    // The index is committed by CI. One that churns on every run buries the one diff a reviewer
    // needs under noise, and makes "nothing changed" indistinguishable from "something did".
    const { sources } = registryWith({
      community: { 'b.yaml': packFile('b', ['a-tool'], [TOOL]), 'a.yaml': packFile('a', ['a-tool']) },
    })
    const first = renderRegistryIndex(buildRegistryIndex({ sources, now: FIXED }))
    const second = renderRegistryIndex(buildRegistryIndex({ sources, now: FIXED }))
    expect(first).toBe(second)
    expect(JSON.parse(first).packs.map((p: { packId: string }) => p.packId)).toEqual(['a', 'b'])
  })

  it('indexes this repository’s own packs as the official tier', () => {
    const index = buildRegistryIndex({
      sources: [{ dir: shippedPacksDir, prefix: 'packs/official', tier: 'official' }],
      now: FIXED,
    })
    expect(index.packs.length).toBeGreaterThan(0)
    expect(index.packs.every((p) => p.tier === 'official')).toBe(true)
    expect(registryIndexSchema.safeParse(index).success).toBe(true)
  })
})

describe('refusals', () => {
  it('refuses a registry holding a pack that does not load', () => {
    // Skipping it instead would make "this pack was deleted" and "this pack is broken" look
    // identical to every client, and only one of those is something to tell somebody about.
    const { sources } = registryWith({ community: { 'broken.yaml': 'pack: [unclosed\n' } })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(RegistryIndexError)
  })

  it('refuses a reference no tier satisfies', () => {
    const { sources } = registryWith({ community: { 'x.yaml': packFile('x', ['nowhere']) } })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(/unknown tool "nowhere"/)
  })

  it('refuses one packId claimed by two tiers', () => {
    // A community pack shadowing an official id would make `tier` meaningless at exactly the
    // moment it matters: an operator looking at the badge to decide whether to trust it.
    const { sources } = registryWith({
      official: { 'dup.yaml': packFile('dup', ['a-tool'], [TOOL]) },
      community: { 'dup.yaml': packFile('dup', ['a-tool']) },
    })
    expect(() => buildRegistryIndex({ sources, now: FIXED })).toThrow(/one id, one home/)
  })
})

describe('the schema a client validates against', () => {
  const valid = () => buildRegistryIndex({
    sources: registryWith({ official: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) } }).sources,
    now: FIXED,
  })

  it.each([
    ['a path escaping the registry', '../../../etc/passwd.yaml'],
    ['an absolute path', '/etc/passwd.yaml'],
    ['traversal in the middle', 'packs/official/../../secret.yaml'],
    ['a non-YAML file', 'packs/official/base.sh'],
  ])('rejects %s', (_label, path) => {
    // Core joins `path` onto a base URL. Without this the index decides what gets fetched, and
    // an index is a file in a repository anyone can send a pull request to.
    const index = { ...valid(), packs: [{ ...valid().packs[0]!, path }] }
    expect(registryIndexSchema.safeParse(index).success).toBe(false)
  })

  it('rejects a digest that is not a lowercase hex sha256', () => {
    for (const sha256 of ['', 'nothex', 'ABCD'.repeat(16), 'a'.repeat(63)]) {
      const index = { ...valid(), packs: [{ ...valid().packs[0]!, sha256 }] }
      expect(registryIndexSchema.safeParse(index).success, sha256).toBe(false)
    }
  })

  it('rejects an unknown version, so a future format cannot be silently misread', () => {
    expect(registryIndexSchema.safeParse({ ...valid(), version: 2 }).success).toBe(false)
  })

  it('rejects an unknown tier rather than treating it as community', () => {
    const index = { ...valid(), packs: [{ ...valid().packs[0]!, tier: 'verified' }] }
    expect(registryIndexSchema.safeParse(index).success).toBe(false)
  })

  it('rejects an unknown key rather than ignoring it', () => {
    expect(registryIndexSchema.safeParse({ ...valid(), signature: 'looks-official' }).success).toBe(false)
  })
})

describe('digests', () => {
  it('sha256Text over a file’s content equals sha256File over the file', () => {
    // The install path verifies what the CDN returned, which arrives as text. If the two
    // digests disagreed, every install would fail a check nothing was wrong with — so the pair
    // is asserted rather than assumed.
    const { root } = registryWith({ official: { 'base.yaml': packFile('base', ['a-tool'], [TOOL]) } })
    const path = join(root, 'packs/official/base.yaml')
    expect(sha256File(path)).toBe(sha256Text(readFileSync(path, 'utf8')))
    expect(sha256File(path)).toHaveLength(64)
  })
})
