// GENERATED by `node scripts/refresh-prices.mjs --azure` — do not edit by hand.
//
// Source: the public Azure Retail Prices API, which needs no credentials and no Azure account.
//   https://prices.azure.com/api/retail/prices
// Reproduce with: node scripts/refresh-prices.mjs --azure
//
// PAY-AS-YOU-GO LINUX ONLY. The feed returns eight meters for a typical size — Spot, Low
// Priority, Windows and Cloud Services variants of each — and only one is what a Linux customer
// pays. The generator refuses to write a size that does not resolve to exactly one such meter,
// rather than taking the first row and advertising a machine at a third of its price.
//
// `fetchedAt` is when WE read it. `effectiveFrom` is the oldest meter start date across this
// table, which is what says how current the numbers themselves are. Both are recorded because
// they are different facts.
//
// Only the PRICE is bundled. A size's vCPU and memory are read live from Microsoft.Compute/skus
// by the provider, on the same call that reports per-subscription availability, so a shape here
// could never disagree with what Azure will actually sell.

export const AZURE_PRICES_FETCHED_AT = '2026-08-13T16:27:23.288Z'
export const AZURE_PRICES_EFFECTIVE_FROM = '2021-11-01T00:00:00Z'
export const AZURE_PRICES_SOURCE = 'https://prices.azure.com/api/retail/prices'

/** The sizes this provider offers. Anything else is not in the catalogue at all. */
export const AZURE_SIZES: string[] = [
  "Standard_B2ls_v2",
  "Standard_B2s_v2",
  "Standard_B4ls_v2",
  "Standard_B4s_v2",
  "Standard_B2pls_v2",
  "Standard_B2ps_v2",
  "Standard_B4pls_v2",
  "Standard_B4ps_v2",
  "Standard_D2s_v5",
  "Standard_D4s_v5",
  "Standard_D2ps_v5",
  "Standard_D4ps_v5"
]

/** region → VM size → USD/hour, pay-as-you-go Linux, tax exclusive. */
export const AZURE_HOURLY_USD: Record<string, Record<string, number>> = {
  "eastus": {
    "Standard_B2ls_v2": 0.0416,
    "Standard_B2pls_v2": 0.0336,
    "Standard_B2ps_v2": 0.0672,
    "Standard_B2s_v2": 0.0832,
    "Standard_B4ls_v2": 0.147,
    "Standard_B4pls_v2": 0.119,
    "Standard_B4ps_v2": 0.134,
    "Standard_B4s_v2": 0.166,
    "Standard_D2ps_v5": 0.077,
    "Standard_D2s_v5": 0.096,
    "Standard_D4ps_v5": 0.154,
    "Standard_D4s_v5": 0.192
  }
}
