// GENERATED by `node scripts/refresh-prices.mjs --hetzner` — do not edit by hand.
//
// FALLBACK ONLY, and empty on purpose. This provider reads prices LIVE from
// `GET /server_types`, which returns them inline on the call `listOfferings()` already makes,
// so this table is consulted only when a type carries no price for the configured location —
// which, on every payload observed so far, never happens. See README.md for the decision.
//
// Refreshing it needs a project token (`HETZNER_TOKEN`), which is why it is opt-in rather than
// part of the default `refresh-prices.mjs` run, and why it ships empty rather than seeded from
// one project's numbers: Hetzner quotes in the PROJECT's billing currency, so a table built
// from one account would be wrong for another.
import type { PriceTable } from './prices.js'

export const BUNDLED_PRICES: PriceTable = {
  fetchedAt: '1970-01-01T00:00:00.000Z',
  currency: 'EUR',
  hourly: {},
}
